### PR TITLE
make gender-neutral pronoun clearer

### PR DESCRIPTION
**Pull request by DatGuy1**

### CODE REVIEW

**Comment by FastLizard4** [comment]
These actually aren't typos; they're a somewhat uncommon kind of gender-neutral pronouns called [Spivak pronouns](https://en.wikipedia.org/wiki/Spivak_pronoun).  It does seem, though, that this is more confusing to people than not, so I'll leave this open and ask the original author of this part of the bot what he thinks - ping @wlritchi.

**Comment by wlritchi** [comment]
No objection to changing this. Eventually I'd like to support various
pronouns via whatever language pack solution we come up with, but for now
standardizing on what people understand makes sense.

On Dec 22, 2016 4:57 PM, "FastLizard4" <notifications@github.com> wrote:

These actually aren't typos; they're a somewhat uncommon kind of
gender-neutral pronouns called Spivak pronouns
<https://en.wikipedia.org/wiki/Spivak_pronoun>. It does seem, though, that
this is more confusing to people than not, so I'll leave this open and ask
the original author of this part of the bot what he thinks - ping @wlritchi
<https://github.com/wlritchi>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LizardNet/LizardIRC-Beancounter/pull/30#issuecomment-268899632>,
or mute the thread

**Comment by FastLizard4** [comment]
Okay, @DatGuy1, just a couple things before I move this over to Gerrit for final review:

* You may wish to add yourself to the AUTHORS.txt file so we can properly credit you for your contributions; the format in the file should be pretty self-explanatory.
* Since this isn't actually a typo you're fixing, as noted above, you may wish to change the title/description of your pull request for accuracy.  The pull request's title and description will be used for the patch that is reviewed in Gerrit and eventually merged into the bot's code.

When you're ready, let me know and I'll move the pull to Gerrit for final review and merging.  Thanks!

**Comment by FastLizard4** [comment]
Pull request moved to Gerrit at https://gerrit.fastlizard4.org/r/#/c/266/

Merged in 7e1866fad8051e62cc7b76ade127a359d5362358

**Pull request closed without merging**
